### ISSUE TITLE
option "-i" is ignored

### ISSUE THREAD

**Issue by SubOptimal** [lpenz/docker-debian-releases#1]
The image name passed as `-i some-image-name` is always ignored.

In the script is will be overridden at this stage

    name=debian-${dist}-${arch}
    image=${image-"$name"}

**Comment by lpenz** [comment]
Have you tested this out? It's actually working for me, because `${image-"$name"}` returns the value of `$image` if the variable is set.

Reference: https://www.tldp.org/LDP/abs/html/parameter-substitution.html#DEFPARAM1

**Comment by SubOptimal** [comment]
Sorry disturbing you. It's working as expected.

The issue was on my system. When I modified the script to make it runnable without sudo i messed up the environment somehow.

**Comment by lpenz** [comment]
Phew! :)
Thanks for looking after this though, and for using the script!
